version: "3"

services:
  traefik:
    image: traefik:2.4
    restart: unless-stopped
    ports:
      - "80:80"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      internal:
        aliases:
          - qasaqees.tech
          - api.qasaqees.tech
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    image: ghcr.io/ahmedhussiien/flickr-api:latest
    container_name: api
    restart: unless-stopped
    environment:
      MONGODB_URL: mongodb://mongo
      REDIS_URL: redis://redis
      NODE_ENV: testTeam
      HOSTNAME: http://api.qasaqees.tech/
      PORT: 3000
    networks:
      - internal
    depends_on:
      - mongo
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=(( Host(`qasaqees.tech`) || Host(`www.qasaqees.tech`) ) && PathPrefix(`/api`)) || Host(`api.qasaqees.tech`)
      - traefik.http.middlewares.backendPathStrip.stripprefix.prefixes=/api
      - traefik.http.middlewares.backendPathStrip.stripprefix.forceSlash=false
      - traefik.http.routers.backend.middlewares=backendPathStrip@docker

  
  frontend:
    image: flickr-frontend
    container_name: frontend
    restart: unless-stopped
    logging:
      driver: none 
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=( Host(`qasaqees.tech`) || Host(`www.qasaqees.tech`) )

  test:
    image: ghcr.io/ahmedhussiien/flickr-test:0036a51e
    container_name: test
    environment:
      URL: http://qasaqees.tech/
      MODE: automated
    networks:
      - internal
    depends_on:
      - api
      - frontend

  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - dbdata:/data/db
    logging:
      driver: none 

  redis:
    image: redis:6.2-alpine
    container_name: redis
    networks:
      - internal
    logging:
      driver: none 

networks:
  internal:

volumes:
  dbdata: